name: tinycolor
description: Flutter Color manipulation and conversion, ported from JS tinycolor
version: 2.0.0

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=1.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pigment: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
